const token =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2QxMDMzZmFjNDY1ODE3OTQ4YTVlNSIsImxvZ2luIjoiQWxleDQ3IiwiaWF0IjoxNjY5MzkyOTMzLCJleHAiOjE2Njk0MzYxMzN9.BbMbAqEhpaQu3TLJgVxo9dht7etzMC3flxXqC6k9OvQ';

export default token;
