const token =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzIyM2UyMDA1NTUxNzU0ZWRiMWNjMCIsImxvZ2luIjoiYWd0dWdjaGlrIiwiaWF0IjoxNjY4NDI1MDY4LCJleHAiOjE2Njg0NjgyNjh9.prRiTbieqZ2sL5t6ciFprKyJXOlwrEtdIG99eyDe5ok';

export default token;
